version: '3'

services:

  kafka-mqtt-connector:
    image: mikeoertli/kafka-mqtt-connector:0.1.0
    restart: unless-stopped
    hostname: kafka-mqtt-connector
    container_name: kafka-mqtt-connector
    environment:
      KAFKA_HOST: localhost #EDITME IP THROUGH WHICH THE KAFKA BROKER WILL BE REACHED
      KAFKA_PORT: 9092
      KAFKA_CLIENT_ID: kafka-mqtt-connector-1
      MQTT_HOST: localhost #EDITME IP THROUGH WHICH THE MQTT BROKER WILL BE REACHED
      MQTT_PORT: 1883
      MQTT_CLIENT_ID: kafka-mqtt-connector-1
      MQTT_QOS: 2
      TOPIC_MAPPING: robotgroup001/robot001>>>test;robotgroup001/robot002>>>test02;robotgroup001/robot003>>>test03 #EDITME mqttTopicA>>>kafkaTopicA;mqttTopicB>>>kafkaTopicB;mqttTopicC>>>kafkaTopicC
