version: '3'

services:

  kafka-mqtt-connector:
    image: mikeoertli/kafka-mqtt-connector:0.1.0
    restart: unless-stopped
    hostname: kafka-mqtt-connector
    container_name: kafka-mqtt-connector
    env_file:
      - env.list
#    networks:
#      - kafka_mqtt_network

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    restart: unless-stopped
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    expose:
      - "1883"
#    networks:
#      - kafka_mqtt_network

  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - env.list
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
#    networks:
#      - kafka_mqtt_network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: unless-stopped
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    env_file:
      - env.list
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - kafka_mqtt_network

#networks:
#  kafka_mqtt_network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.115.0/24
#          gateway: 192.168.115.1
